# -*- coding: utf-8 -*-
"""Information Extraction Lab-7 Part3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ESFIa9geCrO2A3Ey5bOTv1Mjj90VyCBz

**Install Required Libraries**
"""

!pip install spacy pytesseract pillow
!python -m spacy download en_core_web_sm

"""**Import Libraries**"""

import re
import spacy
import json
from PIL import Image
import pytesseract
nlp = spacy.load('en_core_web_sm')
print("All libraries loaded ✅")

"""REGEX FUNCTIONS
**Extract Dates**
"""

def extract_dates(text):
    patterns = [
        r'\d{1,2}/\d{1,2}/\d{4}',
        r'\d{1,2}-\d{1,2}-\d{4}',
        r'\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* \d{1,2},? \d{4}',
        r'\d{4}-\d{2}-\d{2}'
    ]

    dates = []
    for pattern in patterns:
        matches = re.findall(pattern, text)
        dates.extend(matches)
    return dates

# Test
text = "Invoice date: 03/15/2024. Due: March 30, 2024"
print(extract_dates(text))

pattern = r'\$\s?\d+(?:,\d{3})*(?:\.\d{2})'

r'\b\d{2}/\d{2}/\d{4}\b'

r'INV-\d{4}-\d{3}'

"""**Extract Amounts**"""

def extract_amounts(text):
    pattern = r'\$?\d{1,3}(?:,\d{3})*(?:\.\d{2})?'
    amounts = re.findall(pattern, text)

    cleaned = []
    for amount in amounts:
        clean = amount.replace('$', '').replace(',', '')
        cleaned.append(float(clean))

    return cleaned

# Test
text = "Total: $1,250.50. Tax: $125.05"
print(extract_amounts(text))

"""**Extract Invoice Number**"""

def extract_invoice_number(text):
    patterns = [
        r'INV-\d{4}-\d{3}',
        r'#\d{5,}',
        r'ORDER-[A-Z0-9]+',
        r'Invoice (?:Number|#):?\s*([A-Z0-9-]+)'
    ]

    for pattern in patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            return match.group(1) if match.groups() else match.group(0)

    return None

# Test
text = "Invoice Number: INV-2024-001"
print(extract_invoice_number(text))

"""NER (spaCy)
**Basic NER**
"""

text = """Invoice from Acme Corporation
123 Main Street, New York
Contact: John Smith
Date: March 15, 2024
Amount Due: $1,250.50"""

doc = nlp(text)

for ent in doc.ents:
    print(ent.text, "→", ent.label_)

"""**Extract Entities in Dictionary**"""

def extract_entities(text):
    doc = nlp(text)

    entities = {
        'persons': [],
        'organizations': [],
        'locations': [],
        'dates': [],
        'money': []
    }

    for ent in doc.ents:
        if ent.label_ == 'PERSON':
            entities['persons'].append(ent.text)
        elif ent.label_ == 'ORG':
            entities['organizations'].append(ent.text)
        elif ent.label_ in ['GPE', 'LOC']:
            entities['locations'].append(ent.text)
        elif ent.label_ == 'DATE':
            entities['dates'].append(ent.text)
        elif ent.label_ == 'MONEY':
            entities['money'].append(ent.text)

    return entities

print(extract_entities(text))

"""**Visualize**"""

from spacy import displacy

displacy.render(doc, style='ent', jupyter=True)

"""**Upload Image (for OCR)**

PIPELINE
**Process Invoice**
"""

def process_invoice(image_path):
    img = Image.open(image_path)
    text = pytesseract.image_to_string(img)

    invoice_data = {
        'invoice_number': extract_invoice_number(text),
        'dates': extract_dates(text),
        'amounts': extract_amounts(text)
    }

    entities = extract_entities(text)
    invoice_data.update(entities)

    if invoice_data['amounts']:
        invoice_data['total_amount'] = max(invoice_data['amounts'])

    if invoice_data['dates']:
        invoice_data['invoice_date'] = invoice_data['dates'][0]

    return invoice_data

"""**Run It**"""

images = ['New Invoice.webp', 'Image 2.jpg', 'Image 3.jpg']
for img in images:
    print(f"\nProcessing {img}...")
    result = process_invoice(img)
    print(json.dumps(result, indent=2))

"""**Save JSON**"""

with open('extracted_data.json', 'w') as f:
    json.dump(result, f, indent=2)
print("Saved successfully ✅")