# -*- coding: utf-8 -*-
"""Week5_ocr_basics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B8_j0-7_TFVfqm_P9ZkdUo6wZIyZAaaR

## Week 5 Lab:
OCR Basics using Tesseract and EasyOCR

# Extract text from images
Compare OCR methods
Improve accuracy using preprocessing
"""

# Install Tesseract engine and Pytesseract wrapper
!apt-get install tesseract-ocr -qq
!pip install pytesseract opencv-python pillow -q

# Install EasyOCR
!pip install easyocr -q

# Verify installation
import pytesseract
import easyocr
import cv2
from PIL import Image
print("Setup Complete!")

!apt-get install tesseract-ocr -qq
!pip install pytesseract opencv-python pillow easyocr -q

import pytesseract
import cv2
import easyocr
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
import re

image_list = [
    'receipt1.jpg',
    'receipt 2. new.png',
    'blur reciept 3.webp',
    'blur receipt 4.webp',
    'handwritten-text-1.jpg'
]

img = Image.open(image_list[0])
plt.imshow(img)
plt.axis('off')

text = pytesseract.image_to_string(img)
print(text)

img = Image.open(image_list[1])
plt.imshow(img)
plt.axis('off')

text = pytesseract.image_to_string(img)
print(text)

img = Image.open(image_list[2])
plt.imshow(img)
plt.axis('off')

text = pytesseract.image_to_string(img)
print(text)

img = Image.open(image_list[3])
plt.imshow(img)
plt.axis('off')

text = pytesseract.image_to_string(img)
print(text)

img = Image.open(image_list[4])
plt.imshow(img)
plt.axis('off')

text = pytesseract.image_to_string(img)
print(text)

data = pytesseract.image_to_data(img, output_type='dict')
df = pd.DataFrame(data)

df = df[df['text'].str.strip() != '']
df = df[df['conf'] != -1]

print(df[['text', 'conf']])
print("Average Confidence:", df['conf'].mean())

reader = easyocr.Reader(['en'])

result = reader.readtext(image_list[0])

for r in result:
    print(r)

reader = easyocr.Reader(['en'])

result = reader.readtext(image_list[1])

for r in result:
    print(r)

reader = easyocr.Reader(['en'])

result = reader.readtext(image_list[2])

for r in result:
    print(r)

reader = easyocr.Reader(['en'])

result = reader.readtext(image_list[3])

for r in result:
    print(r)

reader = easyocr.Reader(['en'])

result = reader.readtext(image_list[4])

for r in result:
    print(r)

img_cv = cv2.imread(image_list[0])

gray = cv2.cvtColor(img_cv, cv2.COLOR_BGR2GRAY)
denoised = cv2.GaussianBlur(gray, (5,5), 0)

adaptive = cv2.adaptiveThreshold(
    denoised, 255,
    cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
    cv2.THRESH_BINARY, 11, 2
)

plt.imshow(adaptive, cmap='gray')
plt.title("Preprocessed Image")

img_cv = cv2.imread(image_list[1])

gray = cv2.cvtColor(img_cv, cv2.COLOR_BGR2GRAY)
denoised = cv2.GaussianBlur(gray, (5,5), 0)

adaptive = cv2.adaptiveThreshold(
    denoised, 255,
    cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
    cv2.THRESH_BINARY, 11, 2
)

plt.imshow(adaptive, cmap='gray')
plt.title("Preprocessed Image")

img_cv = cv2.imread(image_list[2])

gray = cv2.cvtColor(img_cv, cv2.COLOR_BGR2GRAY)
denoised = cv2.GaussianBlur(gray, (5,5), 0)

adaptive = cv2.adaptiveThreshold(
    denoised, 255,
    cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
    cv2.THRESH_BINARY, 11, 2
)

plt.imshow(adaptive, cmap='gray')
plt.title("Preprocessed Image")

img_cv = cv2.imread(image_list[3])

gray = cv2.cvtColor(img_cv, cv2.COLOR_BGR2GRAY)
denoised = cv2.GaussianBlur(gray, (5,5), 0)

adaptive = cv2.adaptiveThreshold(
    denoised, 255,
    cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
    cv2.THRESH_BINARY, 11, 2
)

plt.imshow(adaptive, cmap='gray')
plt.title("Preprocessed Image")

img_cv = cv2.imread(image_list[4])

gray = cv2.cvtColor(img_cv, cv2.COLOR_BGR2GRAY)
denoised = cv2.GaussianBlur(gray, (5,5), 0)

adaptive = cv2.adaptiveThreshold(
    denoised, 255,
    cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
    cv2.THRESH_BINARY, 11, 2
)

plt.imshow(adaptive, cmap='gray')
plt.title("Preprocessed Image")

text_original = pytesseract.image_to_string(img)
text_processed = pytesseract.image_to_string(Image.fromarray(adaptive))

print("Original:\n", text_original)
print("\nProcessed:\n", text_processed)

def compare_ocr(image_path):
    img = cv2.imread(image_path)

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    denoised = cv2.GaussianBlur(gray, (5,5), 0)

    thresh = cv2.adaptiveThreshold(
        denoised, 255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY, 11, 2
    )

    # Tesseract
    tess_text = pytesseract.image_to_string(thresh)

    # EasyOCR
    easy_result = reader.readtext(image_path)
    easy_text = " ".join([r[1] for r in easy_result])

    return tess_text, easy_text

for img_path in image_list:
    print("\n========================")
    print("Image:", img_path)

    tess, easy = compare_ocr(img_path)

    print("\nTesseract:\n", tess)
    print("\nEasyOCR:\n", easy)

for img_path in image_list:
    tess, _ = compare_ocr(img_path)

    date = re.findall(r'\d{2}/\d{2}/\d{4}', tess)
    total = re.findall(r'\$\d+\.\d+', tess)

    print("\nImage:", img_path)
    print("Date:", date)
    print("Total:", total)

"""## Observations:
Tesseract works well on printed text
EasyOCR performs better on handwritten text
Preprocessing improves OCR accuracy significantly
Adaptive thresholding gives best results for low-quality images
Receipts are easier to process compared to blur receipts
"""