# -*- coding: utf-8 -*-
"""Week6_Advanced_OCR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aQGKvZt-E9ruJKztBQWNY9Mrm9CJom_v
"""

!pip install tensorflow keras opencv-python scikit-image imutils matplotlib

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
import matplotlib.pyplot as plt

image = cv2.imread('Blur.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.imshow(image)
plt.title("Original Image")
plt.axis('off')

image = cv2.imread('Handwritten.jpeg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.imshow(image)
plt.title("Original Image")
plt.axis('off')

image = cv2.imread('Tilted Reciept.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.imshow(image)
plt.title("Original Image")
plt.axis('off')

image = cv2.imread('clear text.webp')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.imshow(image)
plt.title("Original Image")
plt.axis('off')

image = cv2.imread('rotated newspaper.webp')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.imshow(image)
plt.title("Original Image")
plt.axis('off')

image_paths = [
    "Blur.jpg",
    "Handwritten.jpeg",
    "Tilted Reciept.jpg",
    "clear text.webp",
    "rotated newspaper.webp"
]

import cv2
import numpy as np
import matplotlib.pyplot as plt

def process_image(image_path):
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(10,5))

    # ORIGINAL
    plt.subplot(1,4,1)
    plt.imshow(image)
    plt.title("Original")
    plt.axis('off')

    # -------------------------
    # 1. Perspective Transform
    # -------------------------
    h, w = image.shape[:2]
    pts = np.array([
        [0,0],
        [w-1,0],
        [w-1,h-1],
        [0,h-1]
    ], dtype="float32")

    warped = image.copy()  # default (no change)

    plt.subplot(1,4,2)
    plt.imshow(warped)
    plt.title("Perspective")
    plt.axis('off')

    # -------------------------
    # 2. Deskew
    # -------------------------
    gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
    coords = np.column_stack(np.where(gray > 0))

    angle = cv2.minAreaRect(coords)[-1]
    if angle < -45:
        angle = -(90 + angle)
    else:
        angle = -angle

    (h, w) = image.shape[:2]
    center = (w // 2, h // 2)

    M = cv2.getRotationMatrix2D(center, angle, 1.0)
    deskewed = cv2.warpAffine(image, M, (w, h),
                              flags=cv2.INTER_CUBIC,
                              borderMode=cv2.BORDER_REPLICATE)

    plt.subplot(1,4,3)
    plt.imshow(deskewed)
    plt.title("Deskewed")
    plt.axis('off')

    # -------------------------
    # 3. Noise Removal
    # -------------------------
    _, thresh = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY)
    kernel = np.ones((3,3), np.uint8)
    cleaned = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel)

    plt.subplot(1,4,4)
    plt.imshow(cleaned, cmap='gray')
    plt.title("Denoised")
    plt.axis('off')

    plt.suptitle(image_path)
    plt.show()

for path in image_paths:
    process_image(path)

points_dict = {
    "Blur.jpg": np.array([[0,0],[500,0],[500,500],[0,500]], dtype="float32"),

    "Handwritten.jpeg": np.array([[0,0],[600,0],[600,600],[0,600]], dtype="float32"),

    "Tilted Reciept.jpg": np.array([
        [100, 120],
        [400, 100],
        [420, 600],
        [120, 620]
    ], dtype="float32"),

    "clear text.webp": np.array([[0,0],[800,0],[800,800],[0,800]], dtype="float32"),

    "rotated newspaper.webp": np.array([[0,0],[700,0],[700,700],[0,700]], dtype="float32")
}

from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train / 255.0
x_test = x_test / 255.0

x_train = x_train.reshape(-1, 28, 28, 1)
x_test = x_test.reshape(-1, 28, 28, 1)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

loss, acc = model.evaluate(x_test, y_test)
print("Accuracy:", acc)