# -*- coding: utf-8 -*-
"""Week8 Classifier and API

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mWbZFc1m3lVYZYRQUDXbNyYCu_rvzBk9
"""

!pip install fastapi uvicorn python-multipart scikit-learn joblib pyngrok pytesseract

!apt-get install tesseract-ocr -y

import os

folders = [
    '/content/training_data/invoices',
    '/content/training_data/receipts',
    '/content/training_data/contracts',
    '/content/models',
    '/content/api'
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Folders created successfully!")

import os
import pytesseract
from PIL import Image

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

import joblib

def load_documents(data_dir):

    documents = []
    labels = []

    for doc_type in os.listdir(data_dir):

        folder_path = os.path.join(data_dir, doc_type)

        if not os.path.isdir(folder_path):
            continue

        for filename in os.listdir(folder_path):

            file_path = os.path.join(folder_path, filename)

            try:
                img = Image.open(file_path)

                text = pytesseract.image_to_string(img)

                documents.append(text)

                labels.append(doc_type)

            except Exception as e:
                print(f"Error processing {filename}: {e}")

    return documents, labels

documents, labels = load_documents('/content/training_data')

print(f'Loaded {len(documents)} documents')

print(f'Classes: {set(labels)}')

X_train, X_test, y_train, y_test = train_test_split(
    documents,
    labels,
    test_size=0.2,
    random_state=42,
    stratify=labels
)

vectorizer = TfidfVectorizer(
    max_features=1000,
    stop_words='english',
    ngram_range=(1, 2)
)

X_train_vec = vectorizer.fit_transform(X_train)

X_test_vec = vectorizer.transform(X_test)

classifier = LogisticRegression(max_iter=1000)

classifier.fit(X_train_vec, y_train)

y_pred = classifier.predict(X_test_vec)

accuracy = accuracy_score(y_test, y_pred)

print(f'Accuracy: {accuracy:.1%}')

print('\nClassification Report:')

print(classification_report(y_test, y_pred))

joblib.dump(vectorizer, '/content/models/vectorizer.pkl')

joblib.dump(classifier, '/content/models/classifier.pkl')

print("Models saved successfully!")

loaded_vec = joblib.load('/content/models/vectorizer.pkl')

loaded_clf = joblib.load('/content/models/classifier.pkl')

print("Models loaded successfully!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/week7_extraction.py
# 
# import re
# 
# def extract_dates(text):
# 
#     pattern = r'\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b'
# 
#     return re.findall(pattern, text)
# 
# 
# def extract_amounts(text):
# 
#     pattern = r'\$?\d+(?:,\d{3})*(?:\.\d{2})?'
# 
#     return re.findall(pattern, text)
# 
# 
# def extract_entities(text):
# 
#     words = text.split()
# 
#     entities = [word for word in words if word.istitle()]
# 
#     return list(set(entities[:20]))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/api/main.py
# 
# from fastapi import FastAPI, UploadFile, File
# from fastapi.responses import JSONResponse
# 
# from PIL import Image
# 
# import pytesseract
# import joblib
# import io
# import sys
# 
# sys.path.append('/content')
# 
# from week7_extraction import (
#     extract_dates,
#     extract_amounts,
#     extract_entities
# )
# 
# app = FastAPI(
#     title='Document Intelligence API',
#     description='OCR, Classification, and Extraction',
#     version='1.0.0'
# )
# 
# vectorizer = joblib.load('/content/models/vectorizer.pkl')
# classifier = joblib.load('/content/models/classifier.pkl')
# 
# 
# @app.get('/')
# def root():
# 
#     return {
#         'message': 'Document Intelligence API',
#         'version': '1.0.0',
#         'endpoints': [
#             '/classify',
#             '/extract',
#             '/process'
#         ]
#     }
# 
# 
# @app.post('/classify')
# async def classify_document(file: UploadFile = File(...)):
# 
#     try:
# 
#         contents = await file.read()
# 
#         image = Image.open(io.BytesIO(contents))
# 
#         text = pytesseract.image_to_string(image)
# 
#         text_vec = vectorizer.transform([text])
# 
#         prediction = classifier.predict(text_vec)[0]
# 
#         probabilities = classifier.predict_proba(text_vec)[0]
# 
#         confidence = max(probabilities)
# 
#         return {
#             'document_type': prediction,
#             'confidence': float(confidence),
#             'all_probabilities': {
#                 cls: float(prob)
#                 for cls, prob in zip(
#                     classifier.classes_,
#                     probabilities
#                 )
#             }
#         }
# 
#     except Exception as e:
# 
#         return JSONResponse(
#             status_code=500,
#             content={'error': str(e)}
#         )
# 
# 
# @app.post('/extract')
# async def extract_information(file: UploadFile = File(...)):
# 
#     try:
# 
#         contents = await file.read()
# 
#         image = Image.open(io.BytesIO(contents))
# 
#         text = pytesseract.image_to_string(image)
# 
#         dates = extract_dates(text)
# 
#         amounts = extract_amounts(text)
# 
#         entities = extract_entities(text)
# 
#         return {
#             'dates': dates,
#             'amounts': amounts,
#             'entities': entities,
#             'raw_text': text[:500]
#         }
# 
#     except Exception as e:
# 
#         return JSONResponse(
#             status_code=500,
#             content={'error': str(e)}
#         )
# 
# 
# @app.post('/process')
# async def process_document(file: UploadFile = File(...)):
# 
#     try:
# 
#         contents = await file.read()
# 
#         image = Image.open(io.BytesIO(contents))
# 
#         text = pytesseract.image_to_string(image)
# 
#         text_vec = vectorizer.transform([text])
# 
#         doc_type = classifier.predict(text_vec)[0]
# 
#         confidence = max(
#             classifier.predict_proba(text_vec)[0]
#         )
# 
#         extracted_data = {
#             'dates': extract_dates(text),
#             'amounts': extract_amounts(text),
#             'entities': extract_entities(text)
#         }
# 
#         return {
#             'document_type': doc_type,
#             'confidence': float(confidence),
#             'extracted_data': extracted_data,
#             'status': 'success'
#         }
# 
#     except Exception as e:
# 
#         return JSONResponse(
#             status_code=500,
#             content={
#                 'error': str(e),
#                 'status': 'failed'
#             }
#         )

!ngrok config add-authtoken 3DTeNCsZBD9IKIBMyYx5WIhu4Oq_2suLBw1CAi7JBQteJwWsp

!pip install pyngrok

from pyngrok import ngrok

public_url = ngrok.connect(8000)

print(public_url)

!uvicorn api.main:app --host 0.0.0.0 --port 8000